package com.example.datospersonalistalmacen.constants;

public interface SettingsConstants {

    // ----------------- SETTINGS
    String SHARED_SETTINGS_KEY = "SHARED_SETTINGS";

    String URL_SETTINGS_KEY = "URL";
    String FORMAT_SETTINGS_KEY = "FORMAT";
    String STORAGE_TYPE_SETTINGS_KEY = "STORAGE";
    String COMMUNICATION_TYPE_SETTINGS_KEY = "COMMUNICATION";
    String AGE_VISUALIZATION_SETTINGS_KEY = "AGE_VISUALIZATION";
    String DRIVING_LICENSE_VISUALIZATION_SETTINGS_KEY = "DRIVING_LICENSE_VISUALIZATION";
    String REGISTRY_DATE_VISUALIZATION_SETTINGS_KEY = "REGISTRY_DATE_VISUALIZATION";
    String PHONE_VISUALIZATION_SETTINGS_KEY = "PHONE_VISUALIZATION";
    String ENGLISH_LEVEL_VISUALIZATION_SETTINGS_KEY = "ENGLISH_LEVEL_VISUALIZATION";
    enum FORMAT_KEY_VALUES {
        XML,
        JSON
    };
    enum STORAGE_TYPE_KEY_VALUES {
        INTERNAL_MEMORY,
        CONTENT_PROVIDER
    };
    enum COMMUNICATION_KEY_VALUES {
        ASYNC_TASKS
    }

}




