package com.example.datospersonalist;

public interface CONSTANTS {
    // ---------------- INTENT KEYS
    String INTENT_PERSON_OBJECT_KEY = "PERSON_OBJECT";
    String INTENT_ELEMENT_POSITION_TO_MODIFY_KEY = "PERSON_POSITION_ITEM_LISTVIEW";
    String INTENT_ELEMENT_DATA_TO_MODIFY_KEY = "PERSON_DATA_ITEM_LISTVIEW";
    String INTENT_REQUEST_CODE_KEY = "REQUEST_CODE";
    String INTENT_ELEMENT_NEW_PERSON_KEY = "NEW_PERSON_OBJECT";

    // ----------------- INTENT REQUEST CODES
    int LAUNCH_SECOND_ACTIVITY_TO_ADD = 1;
    int LAUNCH_SECOND_ACTIVITY_TO_MODIFY = 2;
}

